# Generated by Django 4.2 on 2023-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='profile1.jpg', upload_to='Media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
